Create a list of 1,000,00 salaries ranging from 50,000 to 150,000

In [2]:
import random

salary_list = [random.randint(50000, 100000) for _ in range(10_000_000)]
salary_list

[89814,
 78162,
 90502,
 96602,
 50555,
 66988,
 62033,
 76456,
 76352,
 51357,
 62015,
 93755,
 99167,
 57684,
 70618,
 53118,
 59654,
 63190,
 58774,
 50132,
 51848,
 83379,
 52371,
 62034,
 74412,
 63988,
 94034,
 51597,
 74450,
 94595,
 58148,
 81253,
 56212,
 92372,
 66624,
 88587,
 53262,
 86386,
 93516,
 81489,
 71191,
 65019,
 68791,
 77866,
 97686,
 76932,
 69357,
 96783,
 95186,
 77780,
 58588,
 72755,
 53897,
 89845,
 61038,
 87248,
 64498,
 86269,
 57848,
 64749,
 93472,
 97686,
 81468,
 64175,
 81810,
 61544,
 51140,
 53558,
 88367,
 72750,
 92412,
 62772,
 72614,
 63928,
 54349,
 94670,
 57546,
 54534,
 59286,
 87472,
 78883,
 54878,
 56655,
 82150,
 73767,
 92043,
 75535,
 91920,
 67986,
 82811,
 86533,
 85029,
 59061,
 68971,
 95242,
 60179,
 68731,
 86523,
 69898,
 84892,
 78151,
 54381,
 82071,
 98249,
 74685,
 60697,
 52968,
 64283,
 83030,
 97784,
 65670,
 93475,
 84061,
 77445,
 91548,
 52023,
 89126,
 50014,
 95367,
 65721,
 97378,
 60226,
 91040,
 71677,
 74136,


In [3]:
import statistics
statistics.mean(salary_list)

74993.9533102

In [4]:
import numpy as np
np.mean(salary_list)

74993.9533102

In [5]:
my_array = np.array([1, 2, 3, 4, 5])
my_array

array([1, 2, 3, 4, 5])

In [6]:
my_array.mean()

3.0

In [7]:
job_titles = np.array(["Data Analyst", "Data Scientist", "Data Engineer", "Machine Learning Engineer", "AI Engineer"])

base_salaries = np.array([60000, 80000, 75000, 90000, np.nan])

bonus_rate = np.array([.05, .1, .08, .12, np.nan])

In [8]:
total_salaries = base_salaries * (1 + bonus_rate)
total_salaries

array([ 63000.,  88000.,  81000., 100800.,     nan])

In [9]:
np.nanmean(total_salaries)

83200.0

In [10]:
# An array representing the number of years fo experience required for three different data science job listing
years_of_experience = np.array([1,2,3,4,5])

#Adding 1 year to the experience requirements for each job posting
years_of_experience_plus_one = years_of_experience + 1
years_of_experience_plus_one

array([2, 3, 4, 5, 6])

In [11]:
# Subtracting 1 year of experience of each job listing
years_of_experience_minus_one = years_of_experience - 1
years_of_experience_minus_one

array([0, 1, 2, 3, 4])

In [12]:
# Doubling the experience for each job listing
years_of_experience_double = years_of_experience * 2
years_of_experience_double

array([ 2,  4,  6,  8, 10])

In [13]:
# Slicing
years_of_experience[1:3]

array([2, 3])

In [14]:
more_than_two = years_of_experience[years_of_experience > 2]
more_than_two

array([3, 4, 5])

Statistics Operations with Numpy

In [15]:
# Mean
salary_array = np.array(salary_list)
average_salary = np.mean(salary_array)
average_salary

74993.9533102

In [16]:
# Median
median_salary = np.median(salary_array)
median_salary

74996.0

In [17]:
# Calculate the standard deviation of the array
salary_std = np.std(salary_array, ddof=1)
salary_std

14437.293057943012

In [18]:
#Minimum element in the salary_array
minimum_salary = np.min(salary_list)
minimum_salary

50000

In [19]:
# Maximum element in the salary_array

In [20]:
max_salary = np.max(salary_array)
max_salary

100000

More practice of Numpy from "Intro to Python for Computer Science and Data Science" by Paul Deitel and Harvey Deitel

In [21]:
# Iterating through a multidimensional array's element
integers = np.array([[1,2,3], [4,5,6], [7, 8, 9]])

for row in integers:
    for column in row:
        print(column, end=" ")
        print()



1 
2 
3 
4 
5 
6 
7 
8 
9 


In [22]:
# Iterating through a multidimensional array as if it was one dimension using flat attribute
for i in integers.flat:
    print(i, end=" ")

1 2 3 4 5 6 7 8 9 

In [25]:
# Creating arrays from ranges
arr1 = np.arange(10)
print(arr1)

arr2 = np.arange(5,9)
print(arr2)

arr3 = np.arange(10, 0, -2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8]
[10  8  6  4  2]


In [26]:
# Creating floating-point ranges using linspace
float_arr = np.linspace(0.0, 1.0, num=5)
print(float_arr)

[0.   0.25 0.5  0.75 1.  ]


In [28]:
# Reshaping an array
arr_4d = np.arange(1,21).reshape (4,5) # Reshaping in a 4 row, 5 column array
print(arr_4d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Shallow copies vs Deep copies
- Shallow copies creates a new object with a pointer to the original object. By modifying the shallow copy, you would also change the original object.
- Deep copies create a new object that is different from the original object. Any changes or modification done to the copy does not affect the original copy

In [32]:
# Examples of shallow copies
numbers = np.arange(1,6)
print(numbers)

# View method return a new array object with a view of the original array
numbers2 = numbers.view()
print(numbers2)

# Checking their IDs. They different objects, so they are supposed to have different IDs
print(id(numbers))
print(id(numbers2))

# Checking what happens if you modify the objects inside each array 
numbers[1] *= 10
print(numbers)
print(numbers2)

numbers2[3] -= 10
print(numbers)
print(numbers2)
# By modifying any object within either array, it changes the other array as well

[1 2 3 4 5]
[1 2 3 4 5]
2465839532144
2465839542896
[ 1 20  3  4  5]
[ 1 20  3  4  5]
[ 1 20  3 -6  5]
[ 1 20  3 -6  5]


In [39]:
# Examples of deep copies using method copy()
numbers = np.arange(1,6)
numbers2 = numbers.copy()

print(numbers)
print(numbers2)

# Checking their IDs
print(id(numbers))
print(id(numbers2))

# Checking what happens if you modify one of the arrays
numbers[3] *= 5
print(numbers)
print(numbers2)
print()

numbers2[1] += 10
print(numbers)
print(numbers2)

[1 2 3 4 5]
[1 2 3 4 5]
2465839542800
2465839541744
[ 1  2  3 20  5]
[1 2 3 4 5]

[ 1  2  3 20  5]
[ 1 12  3  4  5]
